[package]
name = "demo"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.3"
ndarray = "0.14.0"
basic_dsp = "0.9.2"
optargs = { git = "https://github.com/jkelleyrtp/optargs.git" }
